// ============================================================
//  leetcodeData.js  —  Top 100 LeetCode Problems
//  Exports: LEETCODE_PROBLEMS | CATEGORIES | DIFFICULTIES
// ============================================================

export const DIFFICULTIES = ["All", "Easy", "Medium", "Hard"];

export const CATEGORIES = [
  "All", "Array", "String", "Linked List", "Stack",
  "Binary Search", "Sliding Window", "Tree", "Graph",
  "DP", "Heap", "Backtracking", "Bit Manipulation",
];

export const LEETCODE_PROBLEMS = [

  // ── EASY (40) ──────────────────────────────────────────────

  { id:1,  title:"Two Sum",                               difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/two-sum/",                                                    tags:["Hash Map","Array"] },
  { id:2,  title:"Valid Parentheses",                     difficulty:"Easy",   category:"Stack",            link:"https://leetcode.com/problems/valid-parentheses/",                                         tags:["Stack","String"] },
  { id:3,  title:"Merge Two Sorted Lists",                difficulty:"Easy",   category:"Linked List",      link:"https://leetcode.com/problems/merge-two-sorted-lists/",                                    tags:["Linked List","Recursion"] },
  { id:4,  title:"Best Time to Buy and Sell Stock",       difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",                           tags:["Array","Sliding Window"] },
  { id:5,  title:"Valid Anagram",                         difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/valid-anagram/",                                             tags:["Hash Map","String"] },
  { id:6,  title:"Binary Search",                         difficulty:"Easy",   category:"Binary Search",    link:"https://leetcode.com/problems/binary-search/",                                             tags:["Binary Search","Array"] },
  { id:7,  title:"Flood Fill",                            difficulty:"Easy",   category:"Graph",            link:"https://leetcode.com/problems/flood-fill/",                                                tags:["DFS","BFS","Matrix"] },
  { id:8,  title:"Lowest Common Ancestor of BST",         difficulty:"Easy",   category:"Tree",             link:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",            tags:["Tree","BST"] },
  { id:9,  title:"Balanced Binary Tree",                  difficulty:"Easy",   category:"Tree",             link:"https://leetcode.com/problems/balanced-binary-tree/",                                      tags:["Tree","DFS"] },
  { id:10, title:"Linked List Cycle",                     difficulty:"Easy",   category:"Linked List",      link:"https://leetcode.com/problems/linked-list-cycle/",                                         tags:["Linked List","Two Pointers"] },
  { id:11, title:"Implement Queue using Stacks",          difficulty:"Easy",   category:"Stack",            link:"https://leetcode.com/problems/implement-queue-using-stacks/",                              tags:["Stack","Design"] },
  { id:12, title:"First Bad Version",                     difficulty:"Easy",   category:"Binary Search",    link:"https://leetcode.com/problems/first-bad-version/",                                         tags:["Binary Search"] },
  { id:13, title:"Ransom Note",                           difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/ransom-note/",                                               tags:["Hash Map","String"] },
  { id:14, title:"Climbing Stairs",                       difficulty:"Easy",   category:"DP",               link:"https://leetcode.com/problems/climbing-stairs/",                                           tags:["DP","Math"] },
  { id:15, title:"Longest Common Prefix",                 difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/longest-common-prefix/",                                     tags:["String"] },
  { id:16, title:"Contains Duplicate",                    difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/contains-duplicate/",                                        tags:["Array","Hash Set"] },
  { id:17, title:"Missing Number",                        difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/missing-number/",                                            tags:["Array","Math","Bit Manipulation"] },
  { id:18, title:"Reverse Linked List",                   difficulty:"Easy",   category:"Linked List",      link:"https://leetcode.com/problems/reverse-linked-list/",                                       tags:["Linked List","Recursion"] },
  { id:19, title:"Majority Element",                      difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/majority-element/",                                          tags:["Array","Sorting","Boyer-Moore"] },
  { id:20, title:"Move Zeroes",                           difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/move-zeroes/",                                               tags:["Array","Two Pointers"] },
  { id:21, title:"Squares of a Sorted Array",             difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/squares-of-a-sorted-array/",                                 tags:["Array","Two Pointers"] },
  { id:22, title:"Maximum Subarray",                      difficulty:"Easy",   category:"DP",               link:"https://leetcode.com/problems/maximum-subarray/",                                          tags:["Array","DP","Kadane"] },
  { id:23, title:"Number of 1 Bits",                      difficulty:"Easy",   category:"Bit Manipulation", link:"https://leetcode.com/problems/number-of-1-bits/",                                          tags:["Bit Manipulation"] },
  { id:24, title:"Counting Bits",                         difficulty:"Easy",   category:"Bit Manipulation", link:"https://leetcode.com/problems/counting-bits/",                                             tags:["Bit Manipulation","DP"] },
  { id:25, title:"Reverse Bits",                          difficulty:"Easy",   category:"Bit Manipulation", link:"https://leetcode.com/problems/reverse-bits/",                                              tags:["Bit Manipulation"] },
  { id:26, title:"Single Number",                         difficulty:"Easy",   category:"Bit Manipulation", link:"https://leetcode.com/problems/single-number/",                                             tags:["Bit Manipulation","Array"] },
  { id:27, title:"Roman to Integer",                      difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/roman-to-integer/",                                          tags:["Hash Map","Math"] },
  { id:28, title:"Happy Number",                          difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/happy-number/",                                              tags:["Math","Hash Set"] },
  { id:29, title:"Is Subsequence",                        difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/is-subsequence/",                                            tags:["Two Pointers","String"] },
  { id:30, title:"Power of Two",                          difficulty:"Easy",   category:"Bit Manipulation", link:"https://leetcode.com/problems/power-of-two/",                                              tags:["Bit Manipulation","Math"] },
  { id:31, title:"Symmetric Tree",                        difficulty:"Easy",   category:"Tree",             link:"https://leetcode.com/problems/symmetric-tree/",                                            tags:["Tree","DFS","BFS"] },
  { id:32, title:"Diameter of Binary Tree",               difficulty:"Easy",   category:"Tree",             link:"https://leetcode.com/problems/diameter-of-binary-tree/",                                   tags:["Tree","DFS"] },
  { id:33, title:"Middle of the Linked List",             difficulty:"Easy",   category:"Linked List",      link:"https://leetcode.com/problems/middle-of-the-linked-list/",                                 tags:["Linked List","Two Pointers"] },
  { id:34, title:"Search Insert Position",                difficulty:"Easy",   category:"Binary Search",    link:"https://leetcode.com/problems/search-insert-position/",                                    tags:["Binary Search","Array"] },
  { id:35, title:"Palindrome Number",                     difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/palindrome-number/",                                         tags:["Math","String"] },
  { id:36, title:"Excel Sheet Column Number",             difficulty:"Easy",   category:"String",           link:"https://leetcode.com/problems/excel-sheet-column-number/",                                 tags:["Math","String"] },
  { id:37, title:"Find the Duplicate Number",             difficulty:"Easy",   category:"Array",            link:"https://leetcode.com/problems/find-the-duplicate-number/",                                 tags:["Array","Two Pointers"] },
  { id:38, title:"01 Matrix",                             difficulty:"Easy",   category:"Graph",            link:"https://leetcode.com/problems/01-matrix/",                                                 tags:["BFS","Matrix","DP"] },
  { id:39, title:"Convert Binary LL to Integer",          difficulty:"Easy",   category:"Linked List",      link:"https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/",         tags:["Linked List","Bit Manipulation"] },
  { id:40, title:"Longest Substring No Repeat",           difficulty:"Easy",   category:"Sliding Window",   link:"https://leetcode.com/problems/longest-substring-without-repeating-characters/",            tags:["Sliding Window","Hash Map"] },

  // ── MEDIUM (40) ────────────────────────────────────────────

  { id:41, title:"3Sum",                                  difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/3sum/",                                                       tags:["Array","Two Pointers","Sorting"] },
  { id:42, title:"Binary Tree Level Order Traversal",     difficulty:"Medium", category:"Tree",             link:"https://leetcode.com/problems/binary-tree-level-order-traversal/",                         tags:["Tree","BFS"] },
  { id:43, title:"Clone Graph",                           difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/clone-graph/",                                               tags:["Graph","DFS","BFS"] },
  { id:44, title:"Course Schedule",                       difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/course-schedule/",                                           tags:["Graph","Topological Sort"] },
  { id:45, title:"Number of Islands",                     difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/number-of-islands/",                                         tags:["DFS","BFS","Matrix"] },
  { id:46, title:"Rotting Oranges",                       difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/rotting-oranges/",                                           tags:["BFS","Matrix"] },
  { id:47, title:"Search in Rotated Sorted Array",        difficulty:"Medium", category:"Binary Search",    link:"https://leetcode.com/problems/search-in-rotated-sorted-array/",                            tags:["Binary Search","Array"] },
  { id:48, title:"Combination Sum",                       difficulty:"Medium", category:"Backtracking",     link:"https://leetcode.com/problems/combination-sum/",                                           tags:["Backtracking","Array"] },
  { id:49, title:"Permutations",                          difficulty:"Medium", category:"Backtracking",     link:"https://leetcode.com/problems/permutations/",                                              tags:["Backtracking","Array"] },
  { id:50, title:"Subsets",                               difficulty:"Medium", category:"Backtracking",     link:"https://leetcode.com/problems/subsets/",                                                   tags:["Backtracking","Bit Manipulation"] },
  { id:51, title:"Product of Array Except Self",          difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/product-of-array-except-self/",                              tags:["Array","Prefix Sum"] },
  { id:52, title:"Maximum Product Subarray",              difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/maximum-product-subarray/",                                  tags:["Array","DP"] },
  { id:53, title:"Find Min in Rotated Sorted Array",      difficulty:"Medium", category:"Binary Search",    link:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",                      tags:["Binary Search","Array"] },
  { id:54, title:"Container With Most Water",             difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/container-with-most-water/",                                 tags:["Array","Two Pointers","Greedy"] },
  { id:55, title:"Coin Change",                           difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/coin-change/",                                               tags:["DP","BFS"] },
  { id:56, title:"Longest Increasing Subsequence",        difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/longest-increasing-subsequence/",                            tags:["DP","Binary Search"] },
  { id:57, title:"Unique Paths",                          difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/unique-paths/",                                              tags:["DP","Math"] },
  { id:58, title:"Spiral Matrix",                         difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/spiral-matrix/",                                             tags:["Array","Matrix","Simulation"] },
  { id:59, title:"Jump Game",                             difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/jump-game/",                                                 tags:["Array","Greedy","DP"] },
  { id:60, title:"Gas Station",                           difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/gas-station/",                                               tags:["Array","Greedy"] },
  { id:61, title:"Merge Intervals",                       difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/merge-intervals/",                                           tags:["Array","Sorting","Intervals"] },
  { id:62, title:"Non-overlapping Intervals",             difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/non-overlapping-intervals/",                                 tags:["Array","Greedy","Intervals"] },
  { id:63, title:"Kth Largest Element in Array",          difficulty:"Medium", category:"Heap",             link:"https://leetcode.com/problems/kth-largest-element-in-an-array/",                           tags:["Heap","Sorting","Quickselect"] },
  { id:64, title:"Task Scheduler",                        difficulty:"Medium", category:"Heap",             link:"https://leetcode.com/problems/task-scheduler/",                                            tags:["Heap","Greedy","Array"] },
  { id:65, title:"Subarray Sum Equals K",                 difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/subarray-sum-equals-k/",                                     tags:["Array","Hash Map","Prefix Sum"] },
  { id:66, title:"Longest Consecutive Sequence",          difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/longest-consecutive-sequence/",                              tags:["Array","Hash Set"] },
  { id:67, title:"Decode Ways",                           difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/decode-ways/",                                               tags:["String","DP"] },
  { id:68, title:"Word Break",                            difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/word-break/",                                                tags:["DP","BFS","Trie"] },
  { id:69, title:"Construct Binary Tree",                 difficulty:"Medium", category:"Tree",             link:"https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", tags:["Tree","DFS","Divide & Conquer"] },
  { id:70, title:"Kth Smallest Element in BST",           difficulty:"Medium", category:"Tree",             link:"https://leetcode.com/problems/kth-smallest-element-in-a-bst/",                             tags:["Tree","DFS","Binary Search"] },
  { id:71, title:"Validate Binary Search Tree",           difficulty:"Medium", category:"Tree",             link:"https://leetcode.com/problems/validate-binary-search-tree/",                               tags:["Tree","DFS"] },
  { id:72, title:"Design Add and Search Words",           difficulty:"Medium", category:"Tree",             link:"https://leetcode.com/problems/design-add-and-search-words-data-structure/",                tags:["Trie","DFS","Design"] },
  { id:73, title:"Pacific Atlantic Water Flow",           difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/pacific-atlantic-water-flow/",                               tags:["DFS","BFS","Matrix"] },
  { id:74, title:"Longest Palindromic Substring",         difficulty:"Medium", category:"String",           link:"https://leetcode.com/problems/longest-palindromic-substring/",                             tags:["String","DP","Two Pointers"] },
  { id:75, title:"House Robber II",                       difficulty:"Medium", category:"DP",               link:"https://leetcode.com/problems/house-robber-ii/",                                           tags:["DP","Array"] },
  { id:76, title:"Evaluate Division",                     difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/evaluate-division/",                                         tags:["Graph","BFS","DFS"] },
  { id:77, title:"Graph Valid Tree",                      difficulty:"Medium", category:"Graph",            link:"https://leetcode.com/problems/graph-valid-tree/",                                          tags:["Graph","Union Find","DFS"] },
  { id:78, title:"Hand of Straights",                     difficulty:"Medium", category:"Array",            link:"https://leetcode.com/problems/hand-of-straights/",                                         tags:["Array","Greedy","Hash Map"] },
  { id:79, title:"Meeting Rooms II",                      difficulty:"Medium", category:"Heap",             link:"https://leetcode.com/problems/meeting-rooms-ii/",                                          tags:["Heap","Sorting","Greedy"] },
  { id:80, title:"Design Twitter",                        difficulty:"Medium", category:"Heap",             link:"https://leetcode.com/problems/design-twitter/",                                            tags:["Heap","Hash Map","Design"] },

  // ── HARD (20) ──────────────────────────────────────────────

  { id:81, title:"Trapping Rain Water",                   difficulty:"Hard",   category:"Array",            link:"https://leetcode.com/problems/trapping-rain-water/",                                       tags:["Array","Two Pointers","Stack"] },
  { id:82, title:"Median of Two Sorted Arrays",           difficulty:"Hard",   category:"Binary Search",    link:"https://leetcode.com/problems/median-of-two-sorted-arrays/",                               tags:["Binary Search","Divide & Conquer"] },
  { id:83, title:"Minimum Window Substring",              difficulty:"Hard",   category:"Sliding Window",   link:"https://leetcode.com/problems/minimum-window-substring/",                                  tags:["Sliding Window","Hash Map","String"] },
  { id:84, title:"Serialize and Deserialize Binary Tree", difficulty:"Hard",   category:"Tree",             link:"https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",                     tags:["Tree","BFS","Design"] },
  { id:85, title:"Binary Tree Maximum Path Sum",          difficulty:"Hard",   category:"Tree",             link:"https://leetcode.com/problems/binary-tree-maximum-path-sum/",                              tags:["Tree","DFS","DP"] },
  { id:86, title:"Word Search II",                        difficulty:"Hard",   category:"Backtracking",     link:"https://leetcode.com/problems/word-search-ii/",                                            tags:["Trie","Backtracking","Matrix"] },
  { id:87, title:"Find Median from Data Stream",          difficulty:"Hard",   category:"Heap",             link:"https://leetcode.com/problems/find-median-from-data-stream/",                              tags:["Heap","Design"] },
  { id:88, title:"Sliding Window Maximum",                difficulty:"Hard",   category:"Sliding Window",   link:"https://leetcode.com/problems/sliding-window-maximum/",                                    tags:["Sliding Window","Deque","Monotonic"] },
  { id:89, title:"Largest Rectangle in Histogram",        difficulty:"Hard",   category:"Stack",            link:"https://leetcode.com/problems/largest-rectangle-in-histogram/",                            tags:["Stack","Array","Monotonic Stack"] },
  { id:90, title:"Jump Game II",                          difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/jump-game-ii/",                                              tags:["Array","Greedy","DP"] },
  { id:91, title:"Regular Expression Matching",           difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/regular-expression-matching/",                               tags:["String","DP","Recursion"] },
  { id:92, title:"N-Queens",                              difficulty:"Hard",   category:"Backtracking",     link:"https://leetcode.com/problems/n-queens/",                                                  tags:["Backtracking","Array"] },
  { id:93, title:"Alien Dictionary",                      difficulty:"Hard",   category:"Graph",            link:"https://leetcode.com/problems/alien-dictionary/",                                          tags:["Graph","Topological Sort"] },
  { id:94, title:"Word Ladder",                           difficulty:"Hard",   category:"Graph",            link:"https://leetcode.com/problems/word-ladder/",                                               tags:["BFS","Hash Set","String"] },
  { id:95, title:"Edit Distance",                         difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/edit-distance/",                                             tags:["String","DP"] },
  { id:96, title:"Burst Balloons",                        difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/burst-balloons/",                                            tags:["DP","Divide & Conquer"] },
  { id:97, title:"The Skyline Problem",                   difficulty:"Hard",   category:"Heap",             link:"https://leetcode.com/problems/the-skyline-problem/",                                       tags:["Heap","Sweep Line","Array"] },
  { id:98, title:"Count Smaller Numbers After Self",      difficulty:"Hard",   category:"Array",            link:"https://leetcode.com/problems/count-of-smaller-numbers-after-self/",                       tags:["Merge Sort","BIT","Divide & Conquer"] },
  { id:99, title:"Palindrome Partitioning II",            difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/palindrome-partitioning-ii/",                                tags:["String","DP"] },
  { id:100,title:"Minimum Cost to Cut a Stick",           difficulty:"Hard",   category:"DP",               link:"https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",                               tags:["DP","Array"] },
];